services:

  honeypot:
    container_name: honeypot
    
    build:
      context: ./honeypot
      dockerfile: Dockerfile
    
    image: honeypot:honeypot
    
    ports:
      - "2222:2222"
    
    networks:
      - fortress
    
    volumes:
      - ./logs:/var/log/fortress/events
    
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    
    mem_limit : 256m
    cpus: 0.50

    restart: unless-stopped

    read_only: true

    tmpfs:
      - /tmp
      - /run
  logger:
    container_name: logger
    
    build:      
      context: ./logger
      dockerfile: Dockerfile

    image: logger:logger

    networks:
      - fortress

    volumes:
      - ./logs:/var/log/fortress/events:ro
      - ./logs:/var/log/fortress/logs

    mem_limit : 256m
    cpus: 0.50

    restart: unless-stopped

    read_only: true

    tmpfs:
      - /tmp
      - /run
      
    depends_on:
      - honeypot

networks:
  fortress:
    driver: bridge
